/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PhonemeIdRouteImport } from './routes/phoneme.$id'
import { Route as PracticeDayRouteImport } from './routes/practice.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonemeIdRoute = PhonemeIdRouteImport.update({
  id: '/phoneme/$id',
  path: '/phoneme/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeDayRoute = PracticeDayRouteImport.update({
  id: '/practice/$day',
  path: '/practice/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/course': typeof CourseRoute
  '/progress': typeof ProgressRoute
  '/phoneme/$id': typeof PhonemeIdRoute
  '/practice/$day': typeof PracticeDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/course': typeof CourseRoute
  '/progress': typeof ProgressRoute
  '/phoneme/$id': typeof PhonemeIdRoute
  '/practice/$day': typeof PracticeDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/course': typeof CourseRoute
  '/progress': typeof ProgressRoute
  '/phoneme/$id': typeof PhonemeIdRoute
  '/practice/$day': typeof PracticeDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/chart' | '/course' | '/progress' | '/phoneme/$id' | '/practice/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/chart' | '/course' | '/progress' | '/phoneme/$id' | '/practice/$day'
  id:
    | '__root__'
    | '/'
    | '/chart'
    | '/course'
    | '/progress'
    | '/phoneme/$id'
    | '/practice/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartRoute: typeof ChartRoute
  CourseRoute: typeof CourseRoute
  ProgressRoute: typeof ProgressRoute
  PhonemeIdRoute: typeof PhonemeIdRoute
  PracticeDayRoute: typeof PracticeDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phoneme/$id': {
      id: '/phoneme/$id'
      path: '/phoneme/$id'
      fullPath: '/phoneme/$id'
      preLoaderRoute: typeof PhonemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$day': {
      id: '/practice/$day'
      path: '/practice/$day'
      fullPath: '/practice/$day'
      preLoaderRoute: typeof PracticeDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartRoute: ChartRoute,
  CourseRoute: CourseRoute,
  ProgressRoute: ProgressRoute,
  PhonemeIdRoute: PhonemeIdRoute,
  PracticeDayRoute: PracticeDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
